version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      go-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"
    groups:
      npm-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        update-types:
          - "minor"
          - "patch"