services:
  netboot:
    image: ghcr.io/wananle88/netboot
    container_name: netboot
    restart: unless-stopped
    network_mode: host
    command: ["--data-dir", "/data", "--host", "0.0.0.0", "--port", "8088", "--no-browser"]
    volumes:
      - ./data:/data
